require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.lsp_zero')
require('core.plugin_config.vgit')
require('core.plugin_config.undotree')
require('core.plugin_config.fugitive')
